# Generated by Django 4.2.9 on 2026-10-03 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleasedCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_version', models.CharField(max_length=32, verbose_name='策略版本')),
                ('bucket_date', models.DateField(verbose_name='桶日期')),
                ('goods_id', models.BigIntegerField(verbose_name='货物ID')),
                ('category_name', models.CharField(blank=True, max_length=10, verbose_name='品类名称快照')),
                ('variety_name', models.CharField(blank=True, max_length=20, verbose_name='品种名称快照')),
                ('in_count', models.IntegerField(default=0, verbose_name='入库次数')),
                ('in_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='入库数量')),
                ('out_count', models.IntegerField(default=0, verbose_name='出库次数')),
                ('out_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='出库数量')),
                ('frozen_at', models.DateTimeField(auto_now_add=True, verbose_name='冻结时间')),
            ],
            options={
                'verbose_name': '已发布原子单元',
                'verbose_name_plural': '已发布原子单元',
                'db_table': 'rp_released_cell',
                'ordering': ['-bucket_date'],
                'unique_together': {('policy_version', 'bucket_date', 'goods_id')},
            },
        ),
        migrations.CreateModel(
            name='MaskedExportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('preview', '预览'), ('export', '导出')], max_length=20, verbose_name='操作类型')),
                ('requester_role', models.CharField(blank=True, max_length=20, verbose_name='请求人角色')),
                ('purpose', models.CharField(max_length=50, verbose_name='报表用途')),
                ('purpose_label', models.CharField(blank=True, max_length=50, verbose_name='用途名称')),
                ('policy_version', models.CharField(max_length=32, verbose_name='策略版本')),
                ('granularity', models.CharField(max_length=10, verbose_name='时间粒度')),
                ('dimension', models.CharField(max_length=20, verbose_name='统计维度')),
                ('requested_start', models.DateField(verbose_name='请求起始日期')),
                ('requested_end', models.DateField(verbose_name='请求结束日期')),
                ('effective_start', models.DateField(verbose_name='实际起始日期')),
                ('effective_end', models.DateField(verbose_name='实际结束日期')),
                ('k_threshold', models.IntegerField(default=3, verbose_name='小样本阈值')),
                ('strategy', models.CharField(max_length=20, verbose_name='小样本处理策略')),
                ('fields_released', models.JSONField(default=list, verbose_name='发布字段')),
                ('fields_withheld', models.JSONField(default=list, verbose_name='裁剪字段')),
                ('bucket_count', models.IntegerField(default=0, verbose_name='时间桶数')),
                ('row_count', models.IntegerField(default=0, verbose_name='发布行数')),
                ('released_row_count', models.IntegerField(default=0, verbose_name='正常发布行数')),
                ('merged_row_count', models.IntegerField(default=0, verbose_name='合并行数')),
                ('suppressed_cell_count', models.IntegerField(default=0, verbose_name='被抑制单元数')),
                ('suppressed_record_count', models.IntegerField(default=0, verbose_name='被抑制记录数（内部留档）')),
                ('data_fingerprint', models.CharField(max_length=64, verbose_name='数据指纹')),
                ('summary', models.JSONField(default=dict, verbose_name='导出摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masked_export_records', to=settings.AUTH_USER_MODEL, verbose_name='请求人')),
            ],
            options={
                'verbose_name': '脱敏报表导出记录',
                'verbose_name_plural': '脱敏报表导出记录',
                'db_table': 'rp_masked_export_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FrozenBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_version', models.CharField(max_length=32, verbose_name='策略版本')),
                ('bucket_date', models.DateField(verbose_name='桶日期')),
                ('record_count', models.IntegerField(default=0, verbose_name='冻结时源记录数')),
                ('frozen_at', models.DateTimeField(auto_now_add=True, verbose_name='冻结时间')),
            ],
            options={
                'verbose_name': '冻结日期桶',
                'verbose_name_plural': '冻结日期桶',
                'db_table': 'rp_frozen_bucket',
                'ordering': ['-bucket_date'],
                'unique_together': {('policy_version', 'bucket_date')},
            },
        ),
    ]
