# Generated by Django 4.2.9 on 2026-10-03 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymizedBucketSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='快照指纹')),
                ('purpose', models.CharField(max_length=50, verbose_name='报表用途')),
                ('granularity', models.CharField(max_length=10, verbose_name='统计粒度')),
                ('period_key', models.CharField(max_length=20, verbose_name='周期标识')),
                ('period_start', models.DateField(verbose_name='周期开始')),
                ('period_end', models.DateField(verbose_name='周期结束')),
                ('strategy_version', models.CharField(max_length=20, verbose_name='脱敏策略版本')),
                ('payload', models.JSONField(default=dict, verbose_name='脱敏结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='固化时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anonymized_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='首次生成人')),
            ],
            options={
                'verbose_name': '脱敏报表快照',
                'verbose_name_plural': '脱敏报表快照',
                'db_table': 'rp_anonymized_bucket_snapshot',
                'ordering': ['period_start'],
                'indexes': [models.Index(fields=['purpose', 'granularity', 'period_key'], name='rp_anonymiz_purpose_74cd32_idx')],
            },
        ),
    ]
